version: "3"

services:
  web:
    build: .
    container_name: nginx-resume
    restart: unless-stopped
    ports:
     - "8080:80"
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro