version: "3"

services:
  web:
    container_name: nginx-cv
    image: nginx:alpine
    restart: unless-stopped
    expose:
      - 80
      - 443
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  default:
    name: web-network

    